### ISSUE TITLE
import crash

### ISSUE THREAD

**Issue by ryusatgat** [kappactf/loli#1]
When I import a file that is'nt exist, core dumped in loli. (Ubuntu 20.04)
[ryugod.com](https://www.ryugod.com/pages/ide/loli/source:eJxT5lJW8MnPybRS8EjNycnXUQjPL8pJUeRS5uLKzC3ILypRSExKTuHiKk6szMnTUEJRpKQJADZQEoM=)

**Comment by nsychev** [comment]
Hi!

It seems that author removed all posts about this language along with the repository. Fortunately we had a local copy, so we published it in 2019.

In fact, we know that it segfaults almost on any error, but we don't provide any support because we didn't write a line of code here.

I'll archive the repository right now.
